[package]
name = "pgzf"
version = "0.7.5"
edition = "2024"
readme = "README.md"
repository = "https://github.com/dwpeng/pgzf-rs"
license = "MIT"
description = "A Rust library for working with the PGZF file format."

[dependencies]
flate2 = { version = "1.1.9", features = ["zlib-rs"], default-features = false }
crc32fast = "1.5.0"
thiserror = "2.0.18"
clap = { version = "4.6.1", features = ["derive"] }
rayon = "1.12.0"
lru = "0.18.0"

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }

[[bench]]
name = "block_cache"
harness = false

[[bin]]
name = "pgzf"
path = "src/main.rs"

[lib]
name = "pgzf"
path = "src/lib.rs"
